# Generated by Django 4.2.7 on 2023-11-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenya',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
