# Generated by Django 4.2.7 on 2023-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuario_contrasenya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenya',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='a', max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
