# Generated by Django 4.2.7 on 2023-11-13 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_usuario_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idMenu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('importePedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('idPedidoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcionProducto', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMenu',
            fields=[
                ('idProductoMenu', models.AutoField(primary_key=True, serialize=False)),
                ('idMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('idRestaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoRestaurante',
            fields=[
                ('idTipoRestaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='idTipoRestaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tiporestaurante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idRestaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idTipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipoproducto'),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='idTipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipoproducto'),
        ),
    ]
