# Generated by Django 4.2.7 on 2023-11-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menu_pedido_pedidoproducto_producto_productomenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='idRestaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurante'),
            preserve_default=False,
        ),
    ]
