# Generated by Django 4.2.7 on 2023-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tipoproducto_idrestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
