# Generated by Django 4.2.7 on 2023-12-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pedidoproducto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='dia',
        ),
    ]
